name: Aroma
channels:
  - defaults
dependencies:
  - python=3.11.7
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - pip:
    - selenium
    - beautifulsoup4
    - requests
    - chromedriver-autoinstaller
    - undetected-chromedriver
    - tqdm
    - plotly
    - missingno
    - statsmodels